name: Test Docker build

on: [push, pull_request]
jobs:
  tests:
    name: Test Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - run: docker build .